### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by xrnss** [25Karma/25karma.github.io#4]
Was making a pull request, then got this error. 

Failed to compile
./src/pages/PlayerPage/components/Accordions/BedWars.js
Attempted import error: 'BEDWARS' is not exported from 'constants/hypixel' (imported as 'consts').
This error occurred during the build time and cannot be dismissed.

Anyone else got this issue?

**Comment by xrnss** [comment]
This happens after running npm start btw

**Comment by xrnss** [comment]
@amosyu2000

**Comment by ChiefChippy2** [comment]
rename Bedwars.js to BedWars.js in src/constants/hypixel

think same thing with skywars.js

**Comment by xrnss** [comment]
thanks, will try it out tmr

**Comment by amosyu2000** [comment]
Thank you for pointing this out. I've updated the file names in the repo.
